scalar Date

type Entity {
    id: ID!
}

type Workspace {
    id: ID!
    name: String!
    color: String!
    path: String!
    createdAt: Date!
    lastOpenedAt: Date
}

type Settings {
    theme: Theme!
    devBrainPath: String!
    general: GeneralSettings!
    tasks: TaskSettings!
    calendar: CalendarSettings!
}


# Setting types 

enum Theme {
    DARK
}

type GeneralSettings {
    defaultLandingPage: LandingPage!
    launchOnStartup: Boolean!
    openToLastPage: Boolean!
    confirmBeforeDeleting: Boolean!
    confirmBeforeArchiving: Boolean!
    timeFormat: TimeFormat!
}

enum LandingPage {
    HOME
    TASKS
    NOTES
    PROJECTS
    CALENDAR
}

# TWELVE_HOUR <-> '12', TWENTY_FOUR_HOUR <-> '24'.
enum TimeFormat {
    TWELVE_HOUR
    TWENTY_FOUR_HOUR
}

type TaskSettings {
    defaultSort: TaskSortField!
    defaultPriority: TaskPriority!
    defaultDueDate: DefaultDueDate!
    defaultView: TaskListView!
    showCompletedTasks: Boolean!
}

enum TaskSortField {
    PRIORITY
    DUE_DATE
    STATUS
}


enum DefaultDueDate {
    TODAY
    TOMORROW
    NEXT_WEEK
}

enum TaskListView {
    LIST
    GROUP
    BOARD
}

type CalendarSettings {
    timezone: String!
    defaultEventDuration: EventDuration!
    firstDayOfWeek: DayOfWeek!
    defaultView: CalendarView!
}

# FIFTEEN_MINUTES <-> '15m', THIRTY_MINUTES <-> '30m', ONE_HOUR <-> '1h'.
enum EventDuration {
    FIFTEEN_MINUTES
    THIRTY_MINUTES
    ONE_HOUR
}

enum DayOfWeek {
    MONDAY
    SUNDAY
}

enum CalendarView {
    MONTH
    WEEK
    DAY
}

# task types

type Task implements Entity { 
    id: ID!
    title: String!
    description: String
    priority: TaskPriority!
    status: TaskStatus!
    startDate: Date
    dueDate: Date!
    parentTask: Task
    project: Project
    isFavorited: Boolean!
    # linkedEntity?
    # think of theses as "back links"
    taskLink: TaskLink
    taskNote: Note
    pullRequestUrl: String
    completedAt: Date
    updatedAt: Date!
    createdAtAt: Date!
    favoritedAt: Date
    archivedAt: Date
    subTasks: [Task!]!
}

union TaskLink = Note | Event

enum TaskStatus {
    NOT_STARTED
    IN_PROGRESS
    COMPLETED
}

enum TaskPriority {
    LOW
    MEDIUM
    HIGH
}

# Note type
type Note implements Entity {
    id: ID!
    title: String
    preview: String
    # read from the file
    content: String!
    project: Project
    # key thing to not here
    # Task here is basically a back link for task notes
    noteLink: NoteLink
    updatedAt: Date!
    createdAtAt: Date!
    favoritedAt: Date
    archivedAt: Date
}

union NoteLink = Task | Event

type Project implements Entity {
    id: ID!
    title: String!
    description: String
    startDate: Date
    dueDate: Date!
    status: ProjectStatus!
    color: String
    progress: ProjectProgress

    tasks(): [Task!]!
    notes(): [Note!]!


    completedAt: Date
    updatedAt: Date!
    createdAtAt: Date!
    favoritedAt: Date
    archivedAt: Date
}

type ProjectProgress {
    completed: Int!
    inProgress: Int!
    notStarted: Int!
    overdue: Int!
}

enum ProjectStatus {
  NOT_STARTED
  ON_HOLD
  ACTIVE
  COMPLETED
}

# Event type

type Event implements Entity {
    id: ID!
    title: String!
    description: String
    startDate: Date!
    endDate: Date!
    allDay: Boolean!
    location: String
    reccurenceRule: String
    meetingUrl: String
    color: String

    updatedAt: Date!
    createdAt: Date!
    favoritedAt: Date
}

type Mutation {
    createWorkspace(): Workspace!
    deleteWorkspace(): Workspace
    switchWorkspace(id: ID!): Workspace

    updateSettings(): Settings!

    createTaskNote(taskId: ID!)
}

type Query {
    # worksapce
    currentWorkspace: Workspace
    workspaces: [Workspace!]!
    # current workspace settings
    # think about this - should this be under the worksace object?
    settings: Settings!
    
    # entity details query
    task(id: ID!): Task
    note(id: ID!): Note
    event(id: ID!): Event
    project(id: ID!): Project
    worksapce(id: ID!): Workspace

    tasks(filter, sort): [Task!]!
}